### ISSUE TITLE
部署vercel出错

### ISSUE THREAD

**Issue by 006lp** [Lete114/Vercel-Typecho#12]
如图
![Screenshot_2023-12-22-22-17-21-03_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/Lete114/Vercel-Typecho/assets/144674902/86396e04-d5b2-48d2-b71f-0ff52da82557)
同时，无法将你的开源项目设为私有

**Comment by 006lp** [comment]
![Screenshot_2023-12-22-22-39-43-47_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/Lete114/Vercel-Typecho/assets/144674902/52db7de5-e9b7-444f-8407-eb7df00995cf)

![Screenshot_2023-12-22-22-40-55-97_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/Lete114/Vercel-Typecho/assets/144674902/a471c6d2-a3d7-459d-90df-e0de6ecfc62e)

![Screenshot_2023-12-22-22-37-49-35_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/Lete114/Vercel-Typecho/assets/144674902/08ff048b-7538-4771-adae-3180a6bf120c)

**Comment by lete114** [comment]
更新php版本，https://github.com/Lete114/Vercel-Typecho/blob/c2e6faed6b5d253befc306bd534f3ae2d54512aa/vercel.json#L4

**Comment by 006lp** [comment]
> 更新php版本，https://github.com/Lete114/Vercel-Typecho/blob/c2e6faed6b5d253befc306bd534f3ae2d54512aa/vercel.json#L4

改成0.6.0后出现之后的问题

**Comment by 006lp** [comment]
那这个超时怎么办![Screenshot_2023-12-22-22-37-49-35_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/Lete114/Vercel-Typecho/assets/144674902/f28fac11-2eeb-4b5a-a0eb-e485dec816b7)

**Comment by lete114** [comment]
timeout没法解决，除非你升级vercel账户为pro账户

**Comment by 006lp** [comment]
好的谢谢
