### ISSUE TITLE
求助一直报错上传目录无法写入, 请手动将安装目录下的 /usr/uploads 目录的权限设置为可写然后继续升级

### ISSUE THREAD

**Issue by Fei-xiangShi** [Lete114/Vercel-Typecho#5]
用的官方库最新版, 文件权限755, typecho一直装不上, 考虑是不是database的问题?

**Comment by lete114** [comment]
这个我也不是很清楚，因为我对typecho也不是太了解

如果你(大家)有能力的话欢迎pr，共同维护

**Comment by Fei-xiangShi** [comment]
会不会是database权限不够? 我试过freedb, 后来改用自己的云服务器(没有配置过, MariaDB), 都是同样的问题, 请问您用的数据库是什么样呢

**Comment by lete114** [comment]
我用的不是官方最新的，数据库是 [gearhost](https://my.gearhost.com/) 提供的 MySQL 但在半年前他们就不再提供免费数据库了，未来1年内也会陆续清除用户的免费数据库，所以我现在使用hexo搭建静态博客

我想因该不是database的权限问题，因该是新版 typecho 会通过php来操作/usr/uploads这个文件所导致的，也可能是有些主题与这个文件有关系而vercel是没有写入权限的，所以才会报错，当然以上仅仅只是猜测，但vercel确实是禁止对文件进行写入操作的，所以仓库才需要提前配置 `config.inc.php` 文件

**Comment by lete114** [comment]
你可以试试 https://blog.imlete.cn/article/Vercel-Deploy-Typecho.html 评论区置顶评论的方法

**Comment by Fei-xiangShi** [comment]
已经解决, 非常感谢!!!

**Comment by alub518** [comment]
@Fei-xiangShi   可以分享一下解决思路吗？我也是碰到了这样的问题
