### ISSUE TITLE
关于typecho1.2.1按您博客教程部署的报错

### ISSUE THREAD

**Issue by HenryLogic** [Lete114/Vercel-Typecho#9]
fork仓库的情况下报错更莫名奇妙，就不说了。看了作者您的博客，教程非常详细，首先感谢您的付出。

看issue里另一位用户说的，我按博客教程走了一遍，因为现在版本更新了，相对博客教程我做的改动如下。

typecho用的是最新的1.2.1。

install.php里面检测写入权限的代码被我添加了注释，这个方法是参考网上其他人的，不然第一步都过不了，会提示没有写入权限。

vercel.json里面关于php那部分写的0.6.0。作者教程中写的版本号过老vercel已不支持，vercel会部署失败

其他流程一切顺利，目前typecho安装过程是三步，第二步是数据库信息的填写，但第二步点下一步的话会卡住，报错是顶部显示error（就这个词，没其他信息）。怀疑是vercel这边的问题，然后我用虚拟主机安装typecho连数据库试了下，结果第二步过了，第三步填写管理员账号那里又卡住过不了了。同样是报错error。不过此时可以看到数据库中已经生成了文件。我用的数据库是https://www.db4free.net/。

不知道有没有什么解决方法。

**Comment by lete114** [comment]
vercel 官方有个gp数据库，免费的你可以试试

我对php也不是很了解，如果你能解决问题，欢迎pr，我的教程可能比较老了，如果有人愿意写教程到仓库的README.md里也可以，欢迎pr做贡献

**Comment by HenryLogic** [comment]
> vercel 官方有个gp数据库，免费的你可以试试
> 
> 我对php也不是很了解，如果你能解决问题，欢迎pr，我的教程可能比较老了，如果有人愿意写教程到仓库的README.md里也可以，欢迎pr做贡献

谢谢做的教程了，我是个小白，也解决不了了，另外谢谢您推荐的数据库，我有空去看看。

**Comment by HenryLogic** [comment]
> vercel 官方有个gp数据库，免费的你可以试试
> 
> 我对php也不是很了解，如果你能解决问题，欢迎pr，我的教程可能比较老了，如果有人愿意写教程到仓库的README.md里也可以，欢迎pr做贡献

破案了，我上面那个数据库不行，这个免费数据库不稳定，时有时无的非常离谱。

我晚上来看突然发现之前vercel部署的项目正常工作了，然后想着登录typecho后台看看，结果又炸了，vercel504报错，很明显是数据库的问题了。但之前安装博客卡住的问题感觉还是不能全部怪到数据库上，如果各位安装博客卡住，可以先本地把typecho跑起来连上想使用的数据库走完安装三步，先把基本的数据加载出来。然后vercel这边的三步应该就能过了。

**Comment by HenryLogic** [comment]
另外还提一嘴，作者您的博客评论区是挂了？我还蛮想看看其他issue里提到问题的解决方法方法的🤔

**Comment by lete114** [comment]
评论区我关掉了，评论内容也是一些比较老的问题，基本上都是问问题的多
